/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-04-03 15:26:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<! DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head lang=\"en\">\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/scripts/common/assets/css/amazeui.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/styles/login.css\" />\r\n");
      out.write("\r\n");
      out.write("<script>!function(e){var c={nonSecure:\"8123\",secure:\"8124\"},t={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=t[n]+r[n]+\":\"+c[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document);</script></head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"sign\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-1\" data-genuitec-path=\"/microblog/WebRoot/jsp/user/login.jsp\">\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <div class=\"am-g\">\r\n");
      out.write("            <h1>Simple Blog</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <h4 class=\"title\">\r\n");
      out.write("            <div class=\"normal-title\">\r\n");
      out.write("                <a class=\"active\" href=\"/microblog/sign/login.html\">登录</a>\r\n");
      out.write("                <b>·</b>\r\n");
      out.write("                <a id=\"js-sign-up-btn\" href=\"/microblog/sign/register.html\">注册</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </h4>\r\n");
      out.write("        <form action=\"\" method=\"post\" class=\"am-form\">\r\n");
      out.write("            <fieldset class=\"am-form-set\">\r\n");
      out.write("                <div class=\"input-prepend restyle\">\r\n");
      out.write("                    <input placeholder=\"你的昵称\" type=\"text\" value=\"\" name=\"username\" id=\"username\">\r\n");
      out.write("                    <i class=\"am-icon-user\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input-prepend restyle\">\r\n");
      out.write("                    <input placeholder=\"密码\" type=\"text\" value=\"\" name=\"password\" id=\"password\">\r\n");
      out.write("                    <i class=\"am-icon-user\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"remember-btn\">\r\n");
      out.write("                    <input type=\"checkbox\"  value=\"true\" checked=\"checked\" name=\"session[remember_me]\"\r\n");
      out.write("                           id=\"session_remember_me\"><span>记住我</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </fieldset>\r\n");
      out.write("            <div>\r\n");
      out.write("                <input id=\"sign-in\"  name=\"commit\" value=\"登录\" class=\"sign-up-button\" data-disable-with=\"登录\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("<!-- 框架JS -->\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/common/assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/common/assets/js/amazeui.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/scripts/common/layer/layer.js\"></script>\r\n");
      out.write("<!-- 页面事件处理JS -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"/microblog/scripts/login.js\"></script>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
