/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2018-04-03 17:05:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.index;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>BLOG</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/microblog/scripts/common/assets/css/amazeui.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/microblog/scripts/common/assets/css/app.css\">\r\n");
      out.write("\r\n");
      out.write("<script>!function(e){var c={nonSecure:\"8123\",secure:\"8124\"},t={nonSecure:\"http://\",secure:\"https://\"},r={nonSecure:\"127.0.0.1\",secure:\"gapdebug.local.genuitec.com\"},n=\"https:\"===window.location.protocol?\"secure\":\"nonSecure\";script=e.createElement(\"script\"),script.type=\"text/javascript\",script.async=!0,script.src=t[n]+r[n]+\":\"+c[n]+\"/codelive-assets/bundle.js\",e.getElementsByTagName(\"head\")[0].appendChild(script)}(document);</script></head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"blog\">\r\n");
      out.write("<header class=\"am-topbar\" data-genuitec-lp-enabled=\"false\" data-genuitec-file-id=\"wc1-51\" data-genuitec-path=\"/microblog/WebRoot/jsp/index/index.jsp\">\r\n");
      out.write("    <h1 class=\"am-topbar-brand\">\r\n");
      out.write("        <a  class=\"am-active\" href=\"#\">微书</a>\r\n");
      out.write("    </h1>\r\n");
      out.write("\r\n");
      out.write("    <button class=\"am-topbar-btn am-topbar-toggle am-btn am-btn-sm am-btn-success am-show-sm-only\"\r\n");
      out.write("            data-am-collapse=\"{target: '#doc-topbar-collapse'}\"><span class=\"am-sr-only\">导航切换</span> <span\r\n");
      out.write("            class=\"am-icon-bars\"></span></button>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"am-collapse am-topbar-collapse\" id=\"doc-topbar-collapse\">\r\n");
      out.write("        <ul class=\"am-nav am-nav-pills am-topbar-nav\">\r\n");
      out.write("            <li class=\"am-active\"><a href=\"#\">发现</a></li>\r\n");
      out.write("            <li  class=\"am-active\"><a href=\"#\">关注</a></li>\r\n");
      out.write("            <li  class=\"am-active\"><a href=\"#\">消息</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <form method=\"get\" action=\"{% url 'myblog:searchDaily' %}\" class=\"am-topbar-form am-topbar-left am-form-inline\" role=\"search\">\r\n");
      out.write("            <div class=\"am-form-group\">\r\n");
      out.write("                <input type=\"text\" class=\"am-form-field am-input-sm\"id=\"search-data\" name=\"searchVal\">\r\n");
      out.write("                <input type=\"submit\" class=\"search-btn\" id=\"search-btn\" value=\"搜索\">\r\n");
      out.write("                <input type=\"hidden\" name=\"type\" value=\"note\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"am-topbar-right\">\r\n");
      out.write("            {% if username %}\r\n");
      out.write("            <div class=\"am-dropdown\" data-am-dropdown=\"{boundary: '.am-topbar'}\">\r\n");
      out.write("                <button class=\"am-btn am-btn-secondary am-topbar-btn am-btn-sm am-dropdown-toggle\"\r\n");
      out.write("                        data-am-dropdown-toggle>{{ username }} <span class=\"am-icon-caret-down\"></span></button>\r\n");
      out.write("                <ul class=\"am-dropdown-content\">\r\n");
      out.write("                    <li><a href=\"{% url 'myblog:publish' %}\">发布</a></li>\r\n");
      out.write("                    <li><a href=\"{% url 'myblog:setting_basic' %}\">设置</a></li>\r\n");
      out.write("                    <li><a href=\"{% url 'myblog:sign_out' %}\">退出</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            {% else %}\r\n");
      out.write("            <div class=\"am-topbar-right\">\r\n");
      out.write("                <a href=\"/myblog/register\" class=\"am-btn am-btn-primary am-topbar-btn am-btn-sm color\">注册</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"am-topbar-right\">\r\n");
      out.write("                <a href=\"/myblog/login\" class=\"am-btn am-btn-primary am-topbar-btn am-btn-sm\">登录</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            {% endif %}\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"am-g am-g-fixed\" id=\"dataListDiv\">\r\n");
      out.write("    <div class=\"am-u-md-9 am-u-sm-12\" id=\"myDailyList\">\r\n");
      out.write("        {% for field in dailyList %}\r\n");
      out.write("        <div class=\"am-u-lg-12 am-u-md-12 am-u-sm-12 \">\r\n");
      out.write("            <h1><a href=\"/myblog/daily/?dailyid={{ field.id }}\">{{ field.title }} </a></h1>\r\n");
      out.write("            <p>{{ field.body }}</p>\r\n");
      out.write("            <p>{{ field.user_name }} 发布于 {{ field.create_time|date:\"Y-m-d H:i:s\"}}</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        {% endfor %}\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"am-u-md-3 am-u-sm-12\">\r\n");
      out.write("        <div class=\"am-g am-g-fixed\">\r\n");
      out.write("            <h3 class=\"\">最新文章</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                {% for daily in recent_daily_list %}\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"/myblog/daily/?dailyid={{ daily.id }}\">{{ daily.title }}</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                {% empty %}\r\n");
      out.write("                暂无文章！\r\n");
      out.write("                {% endfor %}\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"am-g am-g-fixed\">\r\n");
      out.write("            <h3 class=\"\">归档</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                {% for daily in archives_list %}\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"{% url 'myblog:archives' daily.year daily.month %}\">{{ daily.year }}年{{ daily.month }}月</a> <span style=\"color:#0e90d2\">{{daily.count}}篇</span>\r\n");
      out.write("                </li>\r\n");
      out.write("                {% empty %}\r\n");
      out.write("                暂无归档！\r\n");
      out.write("                {% endfor %}\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"am-g am-g-fixed\">\r\n");
      out.write("            <h3 class=\"\">分类</h3>\r\n");
      out.write("            <ul>\r\n");
      out.write("                {% for category in category_list %}\r\n");
      out.write("                <li>\r\n");
      out.write("                    <a href=\"{% url 'myblog:category' category.id %}\">{{category.name}}</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                {% empty %}\r\n");
      out.write("                暂无分类！\r\n");
      out.write("                {% endfor %}\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"am-g am-g-fixed blog-fixed\" id=\"search\">\r\n");
      out.write("    <div class=\"am-u-md-8 am-u-sm-12\" id=\"search_data\">\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/html\" id=\"js_template\">\r\n");
      out.write("    <div class=\"am-u-lg-12 am-u-md-12 am-u-sm-12 blog-entry-text blog-text-center\" id=\"div_search\">\r\n");
      out.write("        <h1><a href=\"\"> </a></h1>\r\n");
      out.write("        <p></p>\r\n");
      out.write("        <p></p>\r\n");
      out.write("    </div>\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 框架JS -->\r\n");
      out.write("<script src=\"/microblog/scripts/common/assets/js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"/microblog/scripts/common/assets/js/amazeui.min.js\"></script>\r\n");
      out.write("<script src=\"/microblog/scripts/common/layer/layer.js\"></script>\r\n");
      out.write("<!-- 页面事件处理JS -->\r\n");
      out.write("<!-- <script type=\"text/javascript\" src=\"/microblog/scripts/login.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
