DROP TABLE IF EXISTS `DAILY`;
CREATE TABLE `DAILY`(
 `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `TITLE` VARCHAR(50) NOT NULL  COMMENT '标题' ,
  `BODY` VARCHAR(300) NOT NULL  COMMENT '内容',
  `CREATE_TIME` DATETIME NOT NULL ,
  `MODIFIED_TIME` DATETIME  ,
  `CATEGORY_ID` INT(5) NOT NULL   COMMENT '分类',
  `USER_ID` VARCHAR(50) NOT NULL COMMENT '作者',
  `CLICK` INT(10) NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;