DROP TABLE IF EXISTS `USER_LOGIN`;
CREATE TABLE `USER_LOGIN`(
 `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `USERNAME` VARCHAR(20) NOT NULL,
  `PASSWORD` VARCHAR(50) NOT NULL ,
  `CREATE_TIME` DATETIME NOT NULL  ,
  `ROLE_ID` INT(5) NOT NULL DEFAULT 3,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;