DROP TABLE IF EXISTS `USER_DETAILS`;
CREATE TABLE `USER_DETAILS`(
 `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `USER_LOGIN_ID` INT(5) NOT NULL,
  `GENDER` INT(1),
  `IMG_PATH` VARCHAR(50),
  `BIRTHDAY` DATETIME NOT NULL,
  `PROVINCE` INT(11),
  `CITY` INT(11),
  `MARRIAGE` INT(1),
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;