DROP TABLE IF EXISTS `USER_CATEGORY`;
CREATE TABLE `USER_CATEGORY`(
  `ID` INT(5) NOT NULL AUTO_INCREMENT ,
  `USER_LOGIN_ID` INT(5) NOT NULL,
  `CATEGORY_NAME` VARCHAR(50) NOT NULL,
   `IS_DELETE` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`ID`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
